# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_disciplines', to=settings.AUTH_USER_MODEL),
        ),
    ]
