# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='In Centimeters', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='In Kilograms', verbose_name='Weight'),
        ),
    ]
