# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161014_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='In Centimeters', validators=[users.utils.less_than_1000_validator], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='In Kilograms', validators=[users.utils.less_than_1000_validator], verbose_name='Weight'),
        ),
    ]
