# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, default=datetime.date(2016, 11, 14))),
                ('end_date', models.DateField(blank=True, default=datetime.date(2016, 11, 14))),
                ('is_current', models.BooleanField(default=True)),
                ('exercises', models.ManyToManyField(related_name='programs', to='exercises.Exercise')),
            ],
        ),
    ]
