# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='styles',
            field=models.ManyToManyField(related_name='programs', to='styles.Style'),
        ),
    ]
