# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20161116_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='Bench Press', max_length=400),
            preserve_default=False,
        ),
    ]
