# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_styles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_date',
        ),
    ]
