# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20161114_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='exercises',
        ),
    ]
