# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0004_remove_program_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='practioners',
            field=models.ManyToManyField(related_name='programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
