# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_practioners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='practioners',
            new_name='practitioners',
        ),
    ]
