# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20161014_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
