# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinePractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('ended', models.DateField(blank=True)),
                ('notes', markupfield.fields.MarkupField(rendered_field=True)),
                ('notes_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', editable=False, max_length=30)),
                ('times_practiced', models.PositiveIntegerField(blank=True, default=0)),
                ('_notes_rendered', models.TextField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discipline',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_disciplines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discipline',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='disciplinepractice',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='disciplines.Discipline'),
        ),
        migrations.AddField(
            model_name='disciplinepractice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_practices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discipline',
            name='practitioners',
            field=models.ManyToManyField(related_name='practiced_disciplines', through='disciplines.DisciplinePractice', to=settings.AUTH_USER_MODEL),
        ),
    ]
