# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0002_auto_20161014_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinepractice',
            name='times_practiced',
        ),
    ]
